Lecture 0 an 1 succesfully tested. code from Lecture 2 not working because of importError ImportError: cannot import name 'Node', 'DiscreteDistribution', etc from 'pomegranate'